version: '2'

services:

  consumer:
    build:
      context: ../data-consumer
      dockerfile: src/main/docker/Dockerfile.jvm
    hostname: consumer
    container_name: consumer
    environment:
      - QUARKUS_HTTP_PORT=8080
    ports:
      - 8081:8080

  producer:
    build:
      context: ../data-producer
      dockerfile: src/main/docker/Dockerfile.jvm
    hostname: producer
    container_name: producer
    ports:
      - 8080:8080

  grafana:
    image: docker.io/grafana/grafana:latest
    hostname: grafana
    container_name: grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./config/grafana/dashboards/:/opt/dashboards
      - ./config/grafana/custom.yaml:/etc/grafana/provisioning/dashboards/custom.yaml
      - ./config/grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml

  prometheus:
    image: quay.io/prometheus/prometheus:latest
    hostname: prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml